# Generated by Django 2.2.6 on 2019-10-16 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.TextField(null=True)),
                ('task', models.TextField(null=True)),
                ('initial_date', models.DateField(default=datetime.datetime(2019, 10, 16, 15, 53, 11, 724582, tzinfo=utc))),
                ('ending_date', models.DateField(null=True)),
            ],
        ),
    ]
