# Generated by Django 2.2.6 on 2019-10-17 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 17, 18, 21, 10, 150773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.CharField(default='Alejandro Bautista', max_length=120),
        ),
    ]
