# Generated by Django 2.2.6 on 2019-10-22 01:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191017_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 22, 1, 55, 6, 469692, tzinfo=utc)),
        ),
    ]
