# Generated by Django 2.2.6 on 2019-10-27 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191021_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2019, 10, 27, 20, 53, 15, 13590, tzinfo=utc)),
        ),
    ]
