# Generated by Django 2.2.6 on 2019-11-01 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20191027_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 1, 21, 11, 38, 858789, tzinfo=utc)),
        ),
    ]
