# Generated by Django 2.2.6 on 2019-11-01 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20191101_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 1, 21, 51, 23, 579237, tzinfo=utc)),
        ),
    ]
