sudo: required
services:
  - docker

script:
  - docker build -t alexbr9007/nginx ./nginx # build the Dockerfile located in the nginx folder
  - docker build -t alexbr9007/web .         # build the main Dockerfile that is located in the root folder
  - docker build -t alexbr9007/db ./db       # build the Dockerfile located in the db folder

after_success:

  # Log in to the docker CLI
  # Do a sudo docker login in your terminal first
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take your images to docker hub
  # docker push alexbr9007 is the name of your repo. I made the images to be the same as your repo name.
  - docker push alexbr9007/nginx
  - docker push alexbr9007/web
  - docker push alexbr9007/db

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-2
#  app: mydashboard
#  env: Mydashboard-env
#  bucket_name: elasticbeanstalk-us-west-2-401387916447
#  bucket_path: mydashboard
#  on:
#    branch: aws-container
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY