version: "3"

services:
  web: # this is the name of your first container that will be loaded as web_1
    build: . # this is equivalent to sudo docker build . (executes the Dockerfile in the root folder)

    #ports: # Use this only when you are troubleshooting the app without the server nginx
    #  - "3000:8888" # map from your web browser port 3000 to container port 8888 (8888 was created by gunicorn)

    depends_on: # this indicates to run the db before the web service
      - db
    volumes:
      # use the line from below when you want to include the virtual environments which are not necessary
      #- /app/venv
      - .:/app

  nginx: # this is the name of your second container that will be loaded as nginx_1
    build: ./nginx # build the Docker image from the ./nginx folder
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static # from the static folder, map it to the folders from the nginx server
      - ./media:/var/www/media   # from the media folder, map it to the folders from the nginx server

  db: # this is the name of your third container that will be loaded as db_1
    build: ./db
    #image: postgres:11
    environment:
     - PGUSER=postgres
     - PGHOST=postgres
     - PGDATABASE=postgres
     - PGPASSWORD=postgres_password
     - PGPORT=5432

