'''
  If you are deploying this docker app to Heroku then comment all the lines from below and erase the configuration settings from the db in the settings.py file
  becaue it is not necessary.
'''
'''
version: "3"

services:
  web: # this is the name of your first container that will be loaded as web_1
    build: . # this is equivalent to sudo docker build . (executes the Dockerfile in the root folder)

    ports: # Use this only when you are troubleshooting the app without the server nginx
      - "3000:8888" # map from your web browser port 3000 to container port 8888 (8888 was created by gunicorn)

    depends_on: # this indicates to run the db before the web service
      - db
    #volumes:
      #- mydashboard/venv
      #- mydashboard/.:.

  db: # this is the name of your third container that will be loaded as db_1
    #build: ./db
    image: postgres:11
    environment:
     - PGUSER=postgres
     - PGHOST=postgres
     - PGDATABASE=postgres
     - PGPASSWORD=postgres_password
     - PGPORT=5432
'''
