# Generated by Django 2.2.6 on 2020-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=40)),
                ('comments', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
    ]
