# Generated by Django 2.2.6 on 2020-03-19 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 4, 22, 37, 343798, tzinfo=utc)),
        ),
    ]
