# Generated by Django 2.2.6 on 2020-03-18 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20200318_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 5, 11, 32, 699349, tzinfo=utc)),
        ),
    ]
