# Generated by Django 2.2.6 on 2020-03-18 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_auto_20200318_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 5, 12, 25, 905806, tzinfo=utc)),
        ),
    ]
