# Generated by Django 2.2.6 on 2020-03-18 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_auto_20200318_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='initial_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 6, 2, 25, 857834, tzinfo=utc)),
        ),
    ]
